INSERT INTO area_interesse (nome) VALUES
('Administração'),
('Agropecuária / Agricultura'),
('Comunicação / Jornalismo'),
('Construção Civil'),
('Design / Criação'),
('Educação / Ensino'),
('Engenharia'),
('Eventos / Produção Cultural'),
('Finanças / Contabilidade'),
('Gastronomia / Alimentação'),
('Hotelaria / Turismo'),
('Jurídico'),
('Logística'),
('Marketing'),
('Mecânica / Manutenção'),
('Moda / Estilo'),
('Meio Ambiente'),
('Produção / Operacional'),
('Recursos Humanos (RH)'),
('Saúde'),
('Segurança / Vigilância'),
('Transporte / Motorista'),
('Tecnologia da Informação');