module.exports = [
  "Comunicação Assertiva", "Liderança Inspiradora", "Pensamento Crítico", "Resolução de Problemas Complexos", "Inteligência Emocional",
  "Trabalho em Equipe", "Adaptabilidade", "Flexibilidade Cognitiva", "Gestão do Tempo", "Proatividade",
  "Criatividade e Inovação", "Ética Profissional", "Resiliência", "Empatia", "Negociação",
  "Orientação para Resultados", "Tomada de Decisão", "Pensamento Analítico", "Aprendizado Contínuo (Lifelong Learning)", "Colaboração Remota",
  "Gestão de Conflitos", "Escuta Ativa", "Persuasão", "Organização e Planejamento", "Autogestão",
  "Curiosidade Intelectual", "Foco no Cliente", "Diversidade e Inclusão", "Visão Estratégica", "Comunicação Interpessoal",
  "Tolerância ao Estresse", "Automotivação", "Paciência", "Multiculturalidade", "Saber dar e receber Feedback",
  "Liderança de Projetos", "Habilidade Multitarefa", "Foco em Detalhes", "Comunicação Não-Violenta", "Mentalidade de Crescimento (Growth Mindset)",
  "Pensamento Lateral", "Capacidade de Síntese", "Escrita Profissional", "Gestão de Expectativas", "Poder de Convencimento",
  "Raciocínio Lógico", "Segurança Psicológica", "Espírito Empreendedor", "Habilidade de Mentoria", "Iniciativa",
  "Lealdade Organizacional", "Mediação", "Oratória", "Pensamento Sistêmico", "Pontualidade",
  "Prudência", "Relacionamento Interpessoal", "Senso de Urgência", "Sustentabilidade Emocional", "Trabalho sob Pressão",
  "Visão de Dono", "Agilidade de Aprendizado", "Altruísmo", "Ambição Saudável", "Análise de Riscos",
  "Atenção Plena (Mindfulness)", "Autoeficácia", "Autoconfiança", "Capacidade de Argumentação", "Capacidade de Concentração",
  "Capacidade de Delegar", "Capacidade de Influência", "Capacidade de Ouvir", "Carisma", "Coaching",
  "Comprometimento", "Confidencialidade", "Consciência Social", "Construção de Networking", "Controle de Impulsos",
  "Cordialidade", "Coragem Moral", "Determinação", "Dinamismo", "Diplomacia",
  "Disciplina", "Discrição", "Educação Corporativa", "Eficiência Operacional", "Entusiasmo",
  "Equilíbrio Emocional", "Espírito Crítico", "Estabilidade Emocional", "Exigência de Qualidade", "Facilidade de Adaptação",
  "Firmeza de Propósito", "Flexibilidade", "Foco na Solução", "Franqueza", "Generosidade",
  "Gestão da Mudança", "Gestão de Carreira", "Gestão de Crises", "Gestão de Energia", "Gestão de Prioridades",
  "Gratidão", "Habilidade Social", "Humildade", "Idealismo", "Imparcialidade",
  "Independência", "Integridade", "Interpretação de Texto", "Intuição", "Investigação",
  "Julgamento e Tomada de Decisão", "Justiça", "Liderança Colaborativa", "Liderança Situacional", "Lógica de Programação Mental",
  "Manejo de Estresse", "Maturidade Profissional", "Metodicidade", "Moderação", "Negociação de Conflitos",
  "Objetividade", "Otimismo", "Organização Pessoal", "Originalidade", "Ousadia",
  "Paixão pelo que faz", "Percepção Social", "Perseverança", "Persistência", "Planejamento Estratégico",
  "Positividade", "Postura Profissional", "Pragmatismo", "Prevenção de Erros", "Produtividade",
  "Pró-atividade", "Psicologia Positiva", "Qualidade de Vida", "Raciocínio Abstrato", "Raciocínio Rápido",
  "Receptividade", "Reconhecimento de Padrões", "Reflexão", "Relacionamento com Stakeholders", "Relacionamento de Confiança",
  "Respeito às Hierarquias", "Responsabilidade", "Responsabilidade Social", "Rigor Profissional", "Saber Dizer Não",
  "Saber Ouvir", "Saúde Mental", "Segurança da Informação Pessoal", "Sensibilidade Artística", "Sensibilidade Cultural",
  "Senso Comum", "Senso Crítico", "Senso de Justiça", "Senso de Organização", "Senso de Responsabilidade",
  "Seriedade", "Simplicidade", "Sinceridade", "Sociabilidade", "Solidariedade",
  "Superação de Metas", "Tato", "Tenacidade", "Tolerância", "Trabalho em Rede",
  "Transparência", "Urbanidade", "Valorização Humana", "Versatilidade", "Vigor",
  "Visão Ampla", "Visão de Futuro", "Visão Global", "Visão Holística", "Vitalidade",
  "Vontade de Aprender", "Zelo", "Abstração", "Acolhimento", "Afetividade",
  "Agilidade Mental", "Altivez", "Amabilidade", "Análise de Cenários", "Análise de Comportamento",
  "Análise de Dados Humana", "Antifragilidade", "Apoio ao Colega", "Aprendizado com Erros", "Argumentação Lógica",
  "Articulação", "Assiduidade", "Autoanálise", "Autoconhecimento", "Autocontrole",
  "Autocuidado", "Autodesenvolvimento", "Autodisciplina", "Autoestima", "Autoexpressão",
  "Autonomia", "Autorregulação", "Benevolência", "Boas Maneiras", "Bom Humor",
  "Busca por Excelência", "Capacidade de Observação", "Civilidade", "Coerência", "Cognição Social",
  "Comiseração", "Compaixão", "Compostura", "Compreensão", "Conciliação",
  "Concordância", "Confiabilidade", "Conformidade", "Confrontação Construtiva", "Consciência de Classe",
  "Consciência Situacional", "Consideração", "Construção de Consenso", "Controle Emocional", "Cooperatividade",
  "Cortesia", "Credibilidade", "Cuidado", "Cultura de Paz", "Decência",
  "Dedicação", "Desprendimento", "Dever", "Devoção", "Dignidade",
  "Diligência", "Direcionamento", "Divertimento no Trabalho", "Docilidade", "Domínio Próprio"
]